/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as DeferRouteImport } from './routes/defer'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as CompositeRouteImport } from './routes/composite'
import { Route as IndexRouteImport } from './routes/index'

const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferRoute = DeferRouteImport.update({
  id: '/defer',
  path: '/defer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositeRoute = CompositeRouteImport.update({
  id: '/composite',
  path: '/composite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/composite': typeof CompositeRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/defer': typeof DeferRoute
  '/simple': typeof SimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/composite': typeof CompositeRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/defer': typeof DeferRoute
  '/simple': typeof SimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/composite': typeof CompositeRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/defer': typeof DeferRoute
  '/simple': typeof SimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/composite' | '/customScript.js' | '/defer' | '/simple'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/composite' | '/customScript.js' | '/defer' | '/simple'
  id:
    | '__root__'
    | '/'
    | '/composite'
    | '/customScript.js'
    | '/defer'
    | '/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompositeRoute: typeof CompositeRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferRoute: typeof DeferRoute
  SimpleRoute: typeof SimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defer': {
      id: '/defer'
      path: '/defer'
      fullPath: '/defer'
      preLoaderRoute: typeof DeferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composite': {
      id: '/composite'
      path: '/composite'
      fullPath: '/composite'
      preLoaderRoute: typeof CompositeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompositeRoute: CompositeRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferRoute: DeferRoute,
  SimpleRoute: SimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
