/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithSuspenseRouteImport } from './routes/with-suspense'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as NotficationsRouteImport } from './routes/notfications'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as Defer3RouteImport } from './routes/defer3'
import { Route as DeferRouteImport } from './routes/defer'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as CompositeRouteImport } from './routes/composite'
import { Route as IndexRouteImport } from './routes/index'

const WithSuspenseRoute = WithSuspenseRouteImport.update({
  id: '/with-suspense',
  path: '/with-suspense',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const NotficationsRoute = NotficationsRouteImport.update({
  id: '/notfications',
  path: '/notfications',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const Defer3Route = Defer3RouteImport.update({
  id: '/defer3',
  path: '/defer3',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferRoute = DeferRouteImport.update({
  id: '/defer',
  path: '/defer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositeRoute = CompositeRouteImport.update({
  id: '/composite',
  path: '/composite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/composite': typeof CompositeRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/defer': typeof DeferRoute
  '/defer3': typeof Defer3Route
  '/graph': typeof GraphRoute
  '/notfications': typeof NotficationsRoute
  '/simple': typeof SimpleRoute
  '/with-suspense': typeof WithSuspenseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/composite': typeof CompositeRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/defer': typeof DeferRoute
  '/defer3': typeof Defer3Route
  '/graph': typeof GraphRoute
  '/notfications': typeof NotficationsRoute
  '/simple': typeof SimpleRoute
  '/with-suspense': typeof WithSuspenseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/composite': typeof CompositeRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/defer': typeof DeferRoute
  '/defer3': typeof Defer3Route
  '/graph': typeof GraphRoute
  '/notfications': typeof NotficationsRoute
  '/simple': typeof SimpleRoute
  '/with-suspense': typeof WithSuspenseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/composite'
    | '/customScript.js'
    | '/defer'
    | '/defer3'
    | '/graph'
    | '/notfications'
    | '/simple'
    | '/with-suspense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/composite'
    | '/customScript.js'
    | '/defer'
    | '/defer3'
    | '/graph'
    | '/notfications'
    | '/simple'
    | '/with-suspense'
  id:
    | '__root__'
    | '/'
    | '/composite'
    | '/customScript.js'
    | '/defer'
    | '/defer3'
    | '/graph'
    | '/notfications'
    | '/simple'
    | '/with-suspense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompositeRoute: typeof CompositeRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferRoute: typeof DeferRoute
  Defer3Route: typeof Defer3Route
  GraphRoute: typeof GraphRoute
  NotficationsRoute: typeof NotficationsRoute
  SimpleRoute: typeof SimpleRoute
  WithSuspenseRoute: typeof WithSuspenseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/with-suspense': {
      id: '/with-suspense'
      path: '/with-suspense'
      fullPath: '/with-suspense'
      preLoaderRoute: typeof WithSuspenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfications': {
      id: '/notfications'
      path: '/notfications'
      fullPath: '/notfications'
      preLoaderRoute: typeof NotficationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defer3': {
      id: '/defer3'
      path: '/defer3'
      fullPath: '/defer3'
      preLoaderRoute: typeof Defer3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defer': {
      id: '/defer'
      path: '/defer'
      fullPath: '/defer'
      preLoaderRoute: typeof DeferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composite': {
      id: '/composite'
      path: '/composite'
      fullPath: '/composite'
      preLoaderRoute: typeof CompositeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompositeRoute: CompositeRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferRoute: DeferRoute,
  Defer3Route: Defer3Route,
  GraphRoute: GraphRoute,
  NotficationsRoute: NotficationsRoute,
  SimpleRoute: SimpleRoute,
  WithSuspenseRoute: WithSuspenseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
